language: node_js
node_js:
  - "1.4"

branches:
  only:
    - master

before_install:
  - npm install bower -g
  - npm install gulp -g

script:
  - npm install
  - bower install
  - gulp test --verbose

cache:
  directories:
  - bower_components
  - src/client/lib
